# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: Casa Corbella
email: hola@casacorbella.cat
description: "Pàgina web de la Casa Corbella de Cardedeu"
baseurl: ""
url: "http://albertolive.github.io/zeppelin/"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-54122212-1"
googleAnalyticsSiteUrl: "albertolive.github.io"

# Location block
eventLocationName: "Casa Corbella"
eventLocationAddress: "Avinguda Eduard Corbella 1"
eventStartTime: ""
eventStartTimeHumanReadable: ""
eventEndTime: ""
eventEndTimeHumanReadable: ""
eventPlaceCoordinates: "41.64258290000001, 2.356339299999945"
mapCenterCoordinates: "41.64258290000001, 2.356339299999945"
mapMobileCenterCoordinates: "41.64258290000001, 2.356339299999945"

# Logistics Location Block
logisticsMapCenterCoordinates: "41.64258290000001, 2.356339299999945"
logisticsMapMobileCenterCoordinates: "41.64258290000001, 2.356339299999945"

#Tweets feed
twitterHashTag: "casacorbella"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900" # MIRARHO

# Subscribe
subscribeAction: "http://casacorbella.us9.list-manage.com/subscribe?u=f858dc39512f4cc6121cafe63&id=31ec279c52"
subscribeRacontades: "http://casacorbella.us9.list-manage.com/subscribe?u=f858dc39512f4cc6121cafe63&id=3911c35ea0"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p" # MIRARHO AIXO ESTA A SPEAKERS "BECOME A SPEAKER"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Head
metaKeywords: "casa corbella, corbella, cardedeu, esdeveniments, festival fresc, festival, concerts, actes"
twitterAccount: "@casacorbella"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Header
eventDate: "Juliol, 2014"
typeoutTextValues: '"", "COR", "CORBE", "CORBELLA"'

# About Event Block
eventName: "Casa Corbella"

# Team Block
aboutUs: "Aixo es una prova, falta per posar qui som" # MIRARHO

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/ #ARRAY AMB TOTES LES IMATGES

# Footer
gplusFollowUsUrl: "https://plus.google.com/b/108193050919826516538"
twitterFollowUsUrl: "https://twitter.com/intent/user?screen_name=casacorbella"
fbFollowUsUrl: "https://facebook.com/casacorbella"

# Blog
blogCommentsEnabled: true
discusShortName: "casacorbella"

# Racontades
#racontadesTitol: "Meet our themes"
racontadesRows:
 - {title: "Què són?", image: "racontades-0.jpg", details: "Les Racontades són una combinació màgica entre contes i la descoberta de racons que ens fan mirar i sentir aquells espais de manera diferent.<br> A les Racontades, les històries i els llocs s’alien per evocar sensacions i les begudes que s'ofereixen al públic adult ajuden a fer d’aquest espectacle una experiència íntima, divertida, emotiva i inoblidable."}
 #- {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 #- {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Informació
informacio:
 - {title: "Dia", image: "dia.png", info: "8 de Novembre<br>22h"}
 - {title: "Preu", image: "prize-1.png", info: "12€"}
 - {title: "Consumicions", image: "consumicio.jpg", info: "Xarrup de garnatxa i tapa de tardor<br>Copa de cava i tapa dolça"}