# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: Casa Corbella
email: hola@casacorbella.cat
description: "Pàgina web de la Casa Corbella de Cardedeu"
baseurl: ""
url: "http://albertolive.github.io/zeppelin/"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-54122212-1"
googleAnalyticsSiteUrl: "albertolive.github.io"

# Location block
eventLocationName: "Casa Corbella"
eventLocationAddress: "Avinguda Eduard Corbella 1"
eventStartTime: ""
eventStartTimeHumanReadable: ""
eventEndTime: ""
eventEndTimeHumanReadable: ""
eventPlaceCoordinates: "41.64258290000001, 2.356339299999945"
mapCenterCoordinates: "41.64258290000001, 2.356339299999945"
mapMobileCenterCoordinates: "41.64258290000001, 2.356339299999945"

# Logistics Location Block
logisticsMapCenterCoordinates: "41.64258290000001, 2.356339299999945"
logisticsMapMobileCenterCoordinates: "41.64258290000001, 2.356339299999945"

#Tweets feed
twitterHashTag: "casacorbella"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900" # MIRARHO

# Subscribe
subscribeAction: "http://casacorbella.us9.list-manage.com/subscribe?u=f858dc39512f4cc6121cafe63&id=31ec279c52"
subscribeRacontades: "http://casacorbella.us9.list-manage.com/subscribe?u=f858dc39512f4cc6121cafe63&id=3911c35ea0"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p" # MIRARHO AIXO ESTA A SPEAKERS "BECOME A SPEAKER"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Head
metaKeywords: "casa corbella, corbella, cardedeu, esdeveniments, festival fresc, festival, concerts, actes"
twitterAccount: "@casacorbella"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Header
eventDate: "Juliol, 2014"
typeoutTextValues: '"", "COR", "CORBE", "CORBELLA"'

# About Event Block
eventName: "Casa Corbella"

# Team Block
aboutUs: "Aixo es una prova, falta per posar qui som" # MIRARHO

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/ #ARRAY AMB TOTES LES IMATGES

# Footer
gplusFollowUsUrl: "https://plus.google.com/b/108193050919826516538"
twitterFollowUsUrl: "https://twitter.com/intent/user?screen_name=casacorbella"
fbFollowUsUrl: "https://facebook.com/casacorbella"

# Blog
blogCommentsEnabled: true
discusShortName: "casacorbella"

# Historia
#racontadesTitol: "Meet our themes"
historiaRows:
 - {title: "", image: "historia-1.jpg", details: "Voler afirmar amb certesa els orígens de la Casa Diumer és una tasca gairebé impossible on cal rebuscar al fons de les històries de grans nissagues de Cardedeu. La incansable recerca del sr. Josep-Oriol Rovellat Masó, descendent de la família Diumer, ha permès descobrir part de la història desconeguda d’una de les cases més emblemàtiques de Cardedeu."}
 - {title: "", image: "historia-2.jpg", details: "Tot i que l’origen de la família Diumer segueix sent un misteri, sabem que un tal sr. Pau Diumer va comprar la finca al sr. Antoni Bramon, probablement cap a l’any 1687. El sr. Pau Diumer, mica en mica, va anar adquirint la propietat íntegra de la família Bramon i així, va anar ampliant el seu patrimoni. Maria Diumer, filla de Pau Diumer, va seguir l’expansió patrimonial casant-se amb  el sr. Josep Mata, terratinent de Sant Cugat, i d’aquesta manera, es van unir dos patrimonis de gran importància."}
 - {title: "", image: "historia-3.jpg", details: "La casa, situada al centre de la propietat rural de can Diumer que comptava amb una extensió de 129 hectàrees, va  acollir anys més tard, vàries renovacions per ordre del sr. Josep Matas Diumer Vallmajor, l’última,  data de 1860. La unió matrimonial de la seva filla, Maria Matas Diumer, amb el sr. Anton Fontova va donar pas a la següent generació, que ja tenia com a primer cognom Fontova. El gran patrimoni es va anar empetitint amb el repartiment de les herències entre els descendents i també a causa de dificultats econòmiques. D’aquesta manera, la parella hereva de Casa Diumer, va haver de subhastar la casa que va ser adquirida pel sr. Eduard Corbella qui la va posar a nom de la seva dona, la sra. Carolina Esteller. Actualment, la casa és propietat de la família descendent del sr. Leopold Corbella, fill d’Eduard Corbella i està enclavada en la confluència entre l’Avinguda Eduard Corbella i la Diagonal Esteller en honor al matrimoni propietari de la Casa Corbella."}

# Racontades
#racontadesTitol: "Meet our themes"
racontadesRows:
 - {title: "Què són?", image: "racontades-0.jpg", details: "Les Racontades són una combinació màgica entre contes i la descoberta de racons que ens fan mirar i sentir aquells espais de manera diferent.<br><br>A les Racontades, les històries i els llocs s’alien per evocar sensacions i les begudes que s'ofereixen al públic adult ajuden a fer d’aquest espectacle una experiència íntima, divertida, emotiva i inoblidable."}
 - {title: "Tots Sants", image: "racontades-1.jpg", details: "En aquesta nova edició de les Racontades, descobrirem diferents racons de la Casa Corbella al ritme d'històries d'intriga i de misteri. <br><br>El proper 8 de novembre, podreu gaudir d'una proposta singular en un espai únic com Casa Corbella.<br>Reserveu les vostres entrades aquí i porteu-les impreses el 8 de novembre a les 22h. No hi falteu!"}
 #- {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Informació
informacio:
 - {title: "Dia", image: "dia.png", info: "8 de Novembre<br>22h"}
 - {title: "Preu", image: "prize-1.png", info: "12€"}
 - {title: "Consumicions", image: "consumicio.jpg", info: "Xarrup de garnatxa i tapa de tardor<br>Copa de cava i tapa dolça"}