# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: Casa Corbella
email: hola@casacorbella.cat
description: "Pàgina oficial de Casa Corbella de Cardedeu, espai per a la cultura i recuperació de la història de Can Diumer."
descriptionHistoria: "La història i orígens de la família Diumer és una tasca gairebé impossible on cal rebuscar al fons de les històries de grans nissagues de Cardedeu."
descriptionProjecte: "Què s’amaga darrere de les grans portes que tanquen aquest palau al bell mig de Cardedeu? Concerts tenyits de llum i d’encant, petites representacions cuinades..."
descriptionProgramacio: "Tota la programació que es fa, es farà o s'ha fet a Casa Corbella. Festival Fresc, Racontades o concert-vermut són alguna de les propostes."
descriptionFotografies: "Recull fotogràfic de Casa Corbella. Fotografies antigues i actuals de la casa ubicada a Cardedeu. Imatges dels actes com ara el Festival Fresc, Racontades..."
descriptionRactontades: "Les Racontades són una combinació màgica entre contes i la descoberta de racons de Casa Corbella que ens fan mirar i sentir aquest espai de manera diferent."
descriptionResumRacontades: "Resum de les Racontades del 8 de novembre del 2014 a Casa Corbella. Hi trobaràs totes les imatges i el vídeo de l'acte."
descriptionConcertVermut: "Arriba a les portes de Casa Corbella la veu captivadora de la cantautora catalana Meritxell Gené, i ho fa per a delectar el públic amb el seu nou treball..."
descriptionResumConcertVermut: "Resum del concert-vermut que es va dur a terme a Casa Corbella amb la cantautora Meritxell Gené la qual va musicar els poemes de Màrius Torres."
descriptionLaSedDeLaSal: "La Sed de la Sal és un recital amb 14 cançons, construïdes al voltant d'alguns temes clàssics. Veu de Rubén Martínez Santana i piano per Borja Riquelme."
descriptionLaCasa: "Recull de fotografies de Casa Corbella avui en dia. Visualitza la grandesa d'aquest imponent palau al bell mig de Cardedeu."
descriptionHistoriaFotografia: "Un viatge en el temps per veure Casa Corbella en els seus inicis. Fotografies de gran valor històric de Cardedeu."
descriptionActes: "Aquí hi trobaras totes les imatges dels actes que s'han anat fent a Casa Corbella com ara el Festival Fresc, les Racontades o Meritxell Gené."
descriptionFestivalFresc: "El Festival Fresc, petit festival d'estiu de Cardedeu, és l'activitat estrella de Casa Corbella. Petites estructures, petits públics i grans resultats."
descriptionPremsa: "Apartat de premsa de Casa Corbella. Aquí podreu trobar les notícies que surten als principals diaris sobre les activitats que es duen a terme a la casa."
descriptionContacte: "Vols posar-te en contacte amb Casa Corbella? Tens algun dubte, suggeriment o proposta? Estem aquí pel que faci falta. Contacta amb nosaltres!"
baseurl: ""
url: "http://www.casacorbella.cat"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-54122212-1"
googleAnalyticsSiteUrl: "http://www.casacorbella.cat"

# Location block
eventLocationName: "Casa Corbella"
eventLocationAddress: "Avinguda Eduard Corbella 1"
eventStartTime: ""
eventStartTimeHumanReadable: ""
eventEndTime: ""
eventEndTimeHumanReadable: ""
eventPlaceCoordinates: "41.64258290000001, 2.356339299999945"
mapCenterCoordinates: "41.64258290000001, 2.356339299999945"
mapMobileCenterCoordinates: "41.64258290000001, 2.356339299999945"

# Logistics Location Block
logisticsMapCenterCoordinates: "41.64258290000001, 2.356339299999945"
logisticsMapMobileCenterCoordinates: "41.64258290000001, 2.356339299999945"

#Tweets feed
twitterHashTag: "casacorbella"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&amp;cache_interval=900" # MIRARHO

# Subscribe
subscribeAction: "http://casacorbella.us9.list-manage.com/subscribe?u=f858dc39512f4cc6121cafe63&amp;id=d6b01abe84"
subscribeRacontades: "http://casacorbella.us9.list-manage.com/subscribe?u=f858dc39512f4cc6121cafe63&amp;id=d6b01abe84"
subscribeText: "Vols formar part de casa corbella?"
subscribeTextSocis: "Espectacle per a familiars de Casa Corbella. Vols formar part de la família?"

# Documents
c4pUrl: "" # MIRARHO AIXO ESTA A SPEAKERS "BECOME A SPEAKER"
c4sponsorsUrl: ""

# Head
metaKeywords: "casa corbella, corbella, cardedeu, esdeveniments, festival fresc, festival, concerts, actes"
twitterAccount: "@casacorbella"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Header
eventDate: "Juliol, 2014"
typeoutTextValues: '"", "COR", "CORBE", "CORBELLA"'

# About Event Block
eventName: "Casa Corbella"

# Team Block
aboutUs: "" # MIRARHO

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/ #ARRAY AMB TOTES LES IMATGES

# Footer
gplusFollowUsUrl: "https://plus.google.com/b/116777404151158684359/+CasaCorbellaCatCasaCorbella/about"
twitterFollowUsUrl: "https://twitter.com/intent/follow?original_referer=http%3A%2F%2F0.0.0.0%3A4000%2F&amp;region=follow_link&amp;screen_name=casacorbella&amp;tw_p=followbutton&amp;variant=2.0"
fbFollowUsUrl: "https://facebook.com/casacorbella"

# Blog
blogCommentsEnabled: true
discusShortName: "casacorbella"

# Historia
#racontadesTitol: "Meet our themes"
historiaRows:
 - {title: "", image: "historia-1.jpg", details: "Voler afirmar amb certesa els orígens de la família Diumer és una tasca gairebé impossible on cal rebuscar al fons de les històries de grans nissagues de Cardedeu. La incansable recerca del Sr. Josep-Oriol Rovellat Masó, descendent de la família Diumer, ha permès descobrir part de la història desconeguda d’una de les cases més emblemàtiques de Cardedeu."}
 - {title: "", image: "historia-2.jpg", details: "Tot i que l’origen de la família Diumer segueix sent un misteri, sabem que el Sr. Pau Diumer va comprar la finca al Sr. Antoni Bramona entre els segles XVI i XVII. Pau Diumer, mica en mica, va anar adquirint la propietat íntegra de la família Bramona i així, va anar ampliant el seu patrimoni. Va ser en aquella època quan el Sant Josep Oriol va allotjar-se a la masia de la finca Diumer durant les seves estades a Cardedeu. Actualment, la família Rovellat conserva la Relíquia del Sant i l’armari on s’hi desaven els ornaments Sagrats."}
 - {title: "", image: "historia-3.jpg", details: "L’expansió patrimonial dels Diumer va avançar amb el casament de la filla de Pau Diumer, la Sra. Maria Diumer, amb el Sr. Domingo Matas, terratinent de Sant Cugat. D’aquesta manera, es van unir dos patrimonis de gran importància que va anar repartint-se entre els molts hereus i hereves però alhora, es tornava a expandir amb la unió matrimonial amb altres propietaris rurals de Catalunya."}
 - {title: "", image: "historia-4.jpg", details: "La propietat rural de la família Diumer va arribar a ocupar 119 hectàrees que s’estenien des de Can Pelegrí fins al bosc de Can Morató. Era tal l’extensió de la propietat, que cada trimestre es pagaven 500 duros d’or de contribució. La casa Diumer tal i com la coneixem avui dia, es creu que es va construir cap al segle XVIII i va ser tres generacions més endavant, quan el Sr. Josep Matas-Diumer Vallmajor va ordenar diferents renovacions de la casa; l’última que es coneix data de 1860."}
 - {title: "", image: "historia-5.jpg", details: "La unió matrimonial de la seva filla, la Sra. Maria Matas-Diumer Vallmajor, amb el Sr. Anton Fontova Juni va donar pas a la següent i última generació propietària de Can Diumer. El gran patrimoni es va anar empetitint, altra vegada, amb el repartiment de les finques rústiques entre els Fontova, els Abella i els Rovellat i la casa va passar a mans dels Riera, qui per raons desconegudes, van haver de subhastar-la. La casa va ser adquirida pel Sr. Eduard Corbella qui la va posar a nom de la seva dona, la Sra. Carolina Esteller. La casa simbolitzava la unió de la parella en la confluència entre l’Avinguda Eduard Corbella i la Diagonal Esteller. Actualment, la casa és propietat compartida de la família descendent del Sr. Leopold Corbella, un dels fills d’Eduard Corbella."}

#Projecte
projecteRows:
- {title: "", image: , details: "Què s’amaga darrere de les grans portes que tanquen aquest palau al bell mig de Cardedeu? Concerts tenyits de llum i d’encant, petites representacions cuinades amb molt d’art i vespres a la fresca. La cultura és impossible d’abraçar, però a Casa Corbella intentem condensar-la durant uns instants perquè vosaltres la pugueu gaudir."}
- {title: "Com funciona?", image: "transparencia.jpg", details: "“Casa meva és casa vostra, si és que hi ha cases d’algú”, que deia en Sisa. Quan lleis, normes i ignorància limiten propostes originals i diferents, la cultura es cola entre els límits establerts i fa gala de la seva màgia. És així com Casa Corbella pot obrir les seves portes al públic i oferir una programació plena de cultura, sensibilitat i compromís amb la seva història. Però, per a fer-ho, necessita una gran família. Així doncs, tothom qui vulgui formar part de Casa Corbella, només ha d'inscriure's en el nostre llibre de família i d’aquesta manera podrà tenir accés a les festes i sorpreses que ja tenim preparades."}

#Projecte
projecte2Rows:
- {title: "Transperència", image: , details: "Casa Corbella som una entitat sense ànim de lucre amb NIF G-66405028 que organitza actes culturals a Cardedeu. Els beneficis obtinguts de cada espectacle es destinen íntegrament als artistes i un petit marge a l’adequació de la casa. Tots els artistes i tot el públic està assegurat durant la seva estada a Casa Corbella amb una pòlissa de responsabilitat civil que cobreix els possibles incidents que puguin tenir lloc. "}


# Racontades
#racontadesTitol: "Meet our themes"
racontadesRows:
 - {title: "Què són?", image: "racontades-0.jpg", details: "Les Racontades són una combinació màgica entre contes i la descoberta de racons que ens fan mirar i sentir aquells espais de manera diferent.<br><br>A les Racontades, les històries i els llocs s’alien per evocar sensacions i les begudes que s'ofereixen al públic adult ajuden a fer d’aquest espectacle una experiència íntima, divertida, emotiva i inoblidable."}
 - {title: "Tots Sants", image: "racontades-1.jpg", details: "En aquesta nova edició de les Racontades, descobrirem diferents racons de la Casa Corbella al ritme d'històries d'intriga i de misteri. <br><br>El proper 8 de novembre, podreu gaudir d'una proposta singular en un espai únic com Casa Corbella.<br>Reserveu les vostres entrades aquí. Ens veiem el 8 de novembre a les 22h. No hi falteu!"}

# Festival Fresc
#festivalFrescTitol: "Meet our themes"
festivalFrescRows:
 - {title: "Què és?", image: "fresc-1.jpg", details: "El Fresc és el Petit Festival d’Estiu de Cardedeu. Petites perles sonores donant-se cita en un indret privilegiat i ple d’història com és el pati de la Casa Corbella, una masia del segle XVIII i tot un símbol arquitectònic i paisatgístic del municipi. Apostem de manera ferma pels músics més inquiets de casa nostra, esquivant el soroll mediàtic i buscant la complicitat d’una escena autòctona que cal reivindicar. Propostes inquietes i fresques que lliguen amb l’espai i la filosofia d’un projecte que pretén evolucionar sense perdre la transversalitat i el lligam amb el seu públic."}
 - {title: "Microcultura", image: "fresc-2.jpg", details: "Petites estructures, petits públics i grans resultats. El Festival Fresc va néixer basant-se en criteris de proximitat i qualitat per respondre a la demanda cultural de les minories amb un model sostenible que s’emmotlla al context de crisi. Defugim les aglomeracions i els grans esdeveniments per a cercar el diàleg i reduir les distàncies entre l’artista i el públic, oferint un format senzill i proper."}
 - {title: "Qui som", image: "fresc-3.jpg", details: "Som gent de casa. Gent que, com tu, estima la cultura i vol viure-la en tota la seva plenitud. Som Brubaker, empresa cultural de vocació inquieta i amb denominació d’origen cardedeuenca, impulsora d’un projecte d’èxit indiscutible com és l’Esbarjo Verdi i gestora del Centre de Creació i Difusió Musical NAUB1 de Granollers. Per fer del Fresc una realitat hem sumat esforços amb Quesoni, empresa de so també amb un llarg recorregut tant a Cardedeu com a la resta del territori, amb un full de serveis on destaca el suport a la cultura emergent; amb la Casa Corbella, finca històrica i un dels elements més singulars del paisatge cardedeuenc; i amb La Torre Rossa, autèntics mestres de la millor gastronomia italiana plenament arrelats a Cardedeu. Una unió a quatre bandes per a una experiència inoblidable."}

# Concert Vermut
concertVermutRows:
 - {title: "", image: "mertixell-gene.jpg", details: "Arriba a les portes de Casa Corbella la veu captivadora de la cantautora catalana Meritxell Gené, i ho fa per a delectar el públic amb el seu nou treball, <b>“Així t’escau la melangia”</b>, en el que musica els poemes de Màrius Torres, el metge que feia versos… L’esdeveniment tindrà lloc el pròxim dia <b>23 de novembre</b>, a les <b>12:00 hores</b>, al Pati de Casa Corbella i anirà amenitzat per un vermut, que complementarà el clímax de sintonia i complicitat que ens oferirà la cantant. El preu de l’entrada és de <b>5 Euros</b> (3 Euros per als alumnes de català del Consorci per a la Normalització Lingüística). Les portes de Casa Corbella obriran una hora abans de l’espectacle, i hi haurà servei de bar que romandrà obert fins a la fi de l’acte."}

#la Sed De La Sal
laSedDeLaSalRows:
- {title: "", image: "laSedDeLaSal1.jpg", details: "<b>28 febrer</b>, <b>18h</b> Presentació del disc <b>La sed de la sal</b>. La Sed de la Sal és un recital amb 14 cançons, construïdes al voltant d'alguns temes clàssics del repertori pianístic des del període barroc fins al romanticisme. Bach, Beethoven, Schumann són 're-visitats' i -des del respecte reverencial cap a les seves partitures- són intervinguts per generar noves peces musicals; cançons compostes per <b> Rubén Martínez Santana </b> acompanyat al piano per <b> Borja Riquelme </b>."}