# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: Casa Corbella
email: hola@casacorbella.cat
description: "Pàgina web de la Casa Corbella de Cardedeu"
baseurl: ""
url: "http://albertolive.github.io/zeppelin/"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-54122212-1"
googleAnalyticsSiteUrl: "albertolive.github.io"

# Location block
eventLocationName: "Casa Corbella"
eventLocationAddress: "Avinguda Eduard Corbella 1"
eventStartTime: ""
eventStartTimeHumanReadable: ""
eventEndTime: ""
eventEndTimeHumanReadable: ""
eventPlaceCoordinates: "41.64258290000001, 2.356339299999945"
mapCenterCoordinates: "41.64258290000001, 2.356339299999945"
mapMobileCenterCoordinates: "41.64258290000001, 2.356339299999945"

# Logistics Location Block
logisticsMapCenterCoordinates: "41.64258290000001, 2.356339299999945"
logisticsMapMobileCenterCoordinates: "41.64258290000001, 2.356339299999945"

#Tweets feed
twitterHashTag: "casacorbella"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900" # MIRARHO

# Subscribe
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc" # MIRARHO AMB GESTOR DE CORREUS

# Documents
c4pUrl: "http://bit.ly/dfua-c4p" # MIRARHO AIXO ESTA A SPEAKERS "BECOME A SPEAKER"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Head
metaKeywords: "casa corbella, corbella, cardedeu, esdeveniments, festival fresc, festival, concerts, actes"
twitterAccount: "@casacorbella"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Header
eventDate: "Juliol, 2014"
typeoutTextValues: '"", "COR", "CORBE", "CORBELLA"'

# About Event Block
eventName: "Casa Corbella"

# Team Block
aboutUs: "Aixo es una prova, falta per posar qui som" # MIRARHO

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/ #ARRAY AMB TOTES LES IMATGES

# Footer
gplusFollowUsUrl: "https://plus.google.com/b/108193050919826516538"
twitterFollowUsUrl: "https://twitter.com/intent/user?screen_name=casacorbella"
fbFollowUsUrl: "https://facebook.com/casacorbella"

# Blog
blogCommentsEnabled: true
discusShortName: "casacorbella"
